package fa.training.exception;

public class MockFinalException extends Exception {
    public MockFinalException(Throwable cause) {
        super(cause);
    }
}
